

//Initiazlie state variables
component_state = null;
element_state = null;

$(document).ready(function(){
	home = _.template($('#home').html());  
	component = _.template($('#component').html());
	elements = _.template($('#elements').html());

	$("#contentPane").html(home({data: "Some data here later"})); //Setting the home page

    $("body").on('click', '#component1', function (e) { 
        $("#contentPane").html(component({data: {title: "Component I: Presenting and Justifying a Problem and Solution Requirements", 
                                                text: Component1,
                                                img_urls:["img/design_step_1_button.png", "img/design_step_2_button.png", "img/design_step_3_button.png"],
                                                rubric: [ElementA, ElementB, ElementC]} })); 
        $('.ui.accordion').accordion();
    }); 

    $("body").on('click', '#component2', function (e) { 
        $("#contentPane").html(component({data: {title: "Component II: Generating and Defending an Original Solution", 
                                                text: Component2, 
                                                img_urls:["img/design_step_4_button.png", "img/design_step_5_button.png", "img/design_step_6_button.png"],
                                                rubric: [ElementD, ElementE, ElementF]} })); 
        $('.ui.accordion').accordion();
    }); 

    $("body").on('click', '#component3', function (e) { 
        $("#contentPane").html(component({data: {title: "Component III: Constructing and Testing a Prototype", 
                                                text: Component3,
                                                img_urls:["img/design_step_7_button.png", "img/design_step_8_button.png", "img/design_step_9_button.png"],
                                                rubric: [ElementG, ElementH, ElementI]} })); 

        $('.ui.accordion').accordion();
    }); 

    $("body").on('click', '#component4', function (e) { 
        $("#contentPane").html(component({data: {title: "Component IV: Evaluation, Reflection, and Recommendations", 
                                                text: Component4,
                                                img_urls:["img/design_step_10_button.png", "img/design_step_11_button.png", "img/design_step_12_button.png"],
                                                rubric: [ElementJ, ElementK, ElementL]} })); 
        $('.ui.accordion').accordion();
    }); 

    $("body").on('click', '#back_to_menu', function (e) { 
        $("#contentPane").html(home({data: "Some data here later"}));
    }); 
});



/////////////// Static DATA ///////////////

    Component1 = ["Element A: Presentation and Justification of the Problem",
                  "Element B: Documentation and Analysis of Prior Solution Attempts",
                  "Element C: Presentation and Justification of Solution Design Requirements" ];

    Component2 = ["Element D: Design Concept Generation, Analysis, and Selection",
                  "Element E: Application of STEM Principles and Practices",
                  "Element F: Consideration of Design Viability" ];

    Component3 = ["Element G: Construction of a Testable Prototype",
                  "Element H: Prototype Testing and Data Collection Plan",
                  "Element I: Testing, Data Collection and Analysis" ];

    Component4 = ["Element J: Documentation of External Evaluation",
                  "Element K: Reflection on the Design Project",
                  "Element L: Presentation of Designer's Recommendations" ];


    ElementA = ["The identification and/or definition of the problem are missing OR cannot be inferred from information included. A justification of the problem is missing, cannot be inferred from information included as evidence, OR is essentially only the opinion of the researcher." 
    			,"The identification and/or definition of the problem is unclear, is unelaborated, and/or is clearly subjective; any intended justification of the problem does not highlight the concerns of any primary stakeholders and/or is based on sources that are overly general, outdated, and/or of dubious credibility; information included is insufficient to allow for the determination any measurable design requirements."
    			,"The problem is identified only somewhat clearly and/or objectively and defined in a manner that is somewhat superficial and/or minimally elaborated with specific detail; the justification of the problem highlights the concerns of only one or two primary stakeholders and/or may be based on insufficient sources or ones that are outdated or of dubious credibility; although little information included is objective, the justification of the problem offers enough objective detail to allow at least a few design requirements to be determined; however, these may not be ones that are measurable."    			
                ,"The problem is somewhat clearly and objectively identified and defined with adequate depth, and it is sometimes elaborated with specific detail, although some information intended as elaboration may be imprecise or general; the justification of the problem highlights the concerns of at least a few primary stakeholders and is based on at least a few sources which are timely and credible; although not all information included may be objective, the justification of the problem offers enough objective detail to allow at least a few measurable design requirements to be determined."
    			,"The problem is clearly and objectively identified and defined with some depth, and it is generally elaborated with specific detail; the justification of the problem highlights the concerns of some primary stakeholders and is based on various timely and generally credible sources; it offers generally objective detail from which multiple measurable design requirements can be determined." 
    			,"The problem is clearly and objectively identified and defined with considerable depth, and it is well elaborated with specific detail; the justification of the problem highlights the concerns of many primary stakeholders and is based on comprehensive, timely, and consistently credible sources; it offers consistently objective detail from which multiple measurable design requirements can be determined."];
    

    ElementB = ["Documentation of plausible prior attempts to solve the problem and/or related problems is drawn from a wide array of clearly identified and consistently credible sources; the analysis of past and current attempts to solve the problem— including both strengths and shortcomings—is consistently clear, detailed, and supported by relevant data."
                ,"Documentation of existing attempts to solve the problem and/or related problems is drawn from a variety of clearly identified and consistently credible sources; the analysis of past and current attempts to solve the problem—including both strengths and shortcomings— is clear and is generally detailed and supported by relevant data."
                ,"Documentation of existing attempts to solve the problem and/or related problems is drawn from several—but not necessarily varied—clearly identified and generally credible sources; the analysis of past and current attempts to solve the problem—including both strengths and shortcomings— is generally clear and contains some detail and relevant supporting data."
                ,"Documentation of existing attempts to solve the problem and/or related problems is drawn from a limited number of sources, some of which may not be clearly identified and/or credible; the analysis of past and current attempts to solve the problem— including strengths and/or shortcomings—is overly general and contains little detail and/or relevant supporting data."
                ,"Documentation of existing attempts to solve the problem and/or related problems is drawn from only one or two sources that may not be clearly identified and/or credible; the analysis of past and current attempts to solve the problem— including strengths and/or shortcomings—is vague and is missing any relevant details and/or relevant supporting data."
                ,"Documentation of existing attempts to solve the problem and/or related problems is missing or minimal (a single source that is not clearly identified and/or credible) OR cannot be inferred from information intended as analysis of past and/or current attempts to solve the problem."]

    ElementC = ["Design requirements are listed and prioritized, and they are consistently clear and detailed; these design requirements presented are consistently objective, measurable, and they would be highly likely to lead to a tangible and viable solution to the problem identified; there is evidence that requirements represent the needs of, and have been validated by, many if not all primary stakeholder groups."
                ,"Design requirements are listed and prioritized, and they are generally clear and detailed; these design requirements presented are nearly always objective and measurable, and they would be likely to lead to a tangible and viable solution to the problem identified; there is evidence that requirements represent the needs of, and have been validated by, several primary stakeholder groups."
                ,"Design requirements are listed and prioritized, and they are generally clear and somewhat detailed; these design requirements presented are generally objective and measurable, and they have the potential to lead to a tangible and viable solution to the problem identified; there is evidence that requirements represent the needs of, and have been validated by, at least a few primary stakeholder groups."
                ,"Design requirements are listed and prioritized, but some/all of these may be incomplete and/or lack specificity; these design requirements may be only sometimes objective and/or measurable, and it is not clear that they will lead to a tangible and viable solution to the problem identified; there is evidence that the requirements represent the needs, of/and or have been validated by, only one primary stakeholder group."
                ,"An attempt is made to list, format, and prioritize requirements, but these may be partial and/or overly general, making them insufficiently measurable to support a viable solution to the problem identified; there is no evidence that the requirements represent the needs of, or have been validated by, any primary stakeholder groups."
                ,"Design requirements are either not presented or are too vague to be used to outline the measurable attributes of a possible design solution to the problem identified. Back"]

    ElementD = ["The process for generating and comparing possible design solutions was comprehensive, iterative, and consistently defensible, making a viable and well- justified design highly likely; the design solution ultimately chosen was well- justified and demonstrated attention to all design requirements; the plan of action has considerable merit and would easily support repetition and testing for effectiveness by others."
                ,"The process for generating and comparing possible design solutions was thorough, iterative, and generally defensible, making a viable design likely; the design solution chosen was justified and demonstrated attention to most if not all design requirements; the plan of action would support repetition and testing for effectiveness by others."
                ,"The process for generating and comparing possible design solutions was adequate and generally iterative and defensible, making a viable design possible; the choice of design solution was explained with reference to at least some design requirements; the plan of action might not clearly or fully support repetition and testing for effectiveness by others."
                ,"The process for generating a possible design solution was partial or overly general and only somewhat iterative and/or defensible, raising issues with the viability of the design solution chosen; that solution was not sufficiently explained with reference to design requirements; there is insufficient detail to allow for testing for replication of results."
                ,"The process for generating a possible design solution was incomplete and was only minimally iterative and/or defensible; any attempted explanation for the design solution chosen lacked support related to design requirements and cannot be tested."
                ,"There is no evidence an attempt to arrive at a design solution through an iterative process based on design requirements."]

    ElementE = ["The proposed solution is well-substantiated with STEM principles and practices applicable to all or nearly all design requirements and functional claims; there is substantial evidence that the application of those principles and practices by the student or a suitable alternate has been reviewed by two or more experts(qualified consultants and/or project mentors) and that those reviews provide confirmation (verification) or detail necessary to inform a corrective response."
                ,"The proposed solution is generally substantiated with STEM principles and practices applicable to some design requirements and functional claims; there is some evidence that the application of those principles and practices by the student or a suitable alternate has been reviewed by at least two experts (qualified consultants and/or project mentors) and that those reviews provide confirmation (verification) or some detail necessary to inform a corrective response."
                ,"The proposed solution is partially substantiated with STEM principles and practices applicable to at least a few design requirements and functional claims; there is some evidence that the application of those principles and practices by the student or a suitable alternate has been reviewed by at least one expert (qualified consultant or project mentor) but this review may not provide clear confirmation (verification) or at least some detail to inform a corrective response."
                ,"The proposed solution is minimally substantiated with STEM principles and practices applicable to at least a few design requirements and functional claims; there is minimal evidence that the application of those principles and practices by the student or a suitable alternate has been reviewed by at least one expert (qualified consultant or project mentor) but there is no evidence of confirmation (verification) or any detail to inform a corrective response."
                ,"The proposed solution is minimally substantiated with STEM principles or practices applicable to at least a few design requirements and functional claims; however, there is no evidence that the application of those principles and practices by the student or a suitable alternate has been reviewed by an expert (qualified consultant or project mentor)."
                ,"The proposed solution is not substantiated with STEM principles or practices applicable to any design requirements and/or functional claims."]

    ElementF = ["The proposed design was carefully reviewed based on several relevant extra- functional considerations; a judgment about design viability based on those considerations—the capacity of the proposed solution to address the problem—is clearly realistic and well supported with credible evidence."
                ,"The proposed design was adequately reviewed based on several relevant extra- functional considerations; a judgment about design viability based on those considerations—the capacity of the proposed solution to address the problem—is generally realistic and adequately supported with credible evidence."
                ,"The proposed design was partially reviewed based on one or two relevant extra- functional considerations; a judgment about design viability based on those considerations—the capacity of the proposed solution to address the problem—is only somewhat/sometimes realistic and is only partially supported with credible evidence."
                ,"The proposed design was superficially reviewed based on one or two relevant extra-functional considerations; a judgment about design viability based on those considerations—the capacity of the proposed solution to address the problem— may be generally although not completely unrealistic and/or may be inadequately supported with credible evidence."
                ,"The proposed design was superficially reviewed based on one or two extra- functional considerations of marginal relevance; a judgment about design viability based on those considerations— the capacity of the proposed solution to address the problem—may be unrealistic and/or not supported with any credible evidence."
                ,"There is no evidence provided that the proposed design was reviewed based on any extra-functional considerations."]

    ElementG = ["The final prototype iteration is clearly and fully explained and is constructed with enough detail to assure that objective data on all or nearly all design requirements could be determined; all attributes (sub-systems) of the unique solution that can be tested or modeled mathematically are addressed and a well- supported justification is provided for those that cannot be tested or modeled mathematically and thus require expert review."
                ,"The final prototype iteration is clearly and adequately explained and is constructed with enough detail to assure that objective data on many design requirements could be determined; most attributes (sub-systems) of the unique solution that can be tested or modeled mathematically are addressed and a generally supported justification is provided for those that cannot be tested or modeled mathematically and thus require expert review."
                ,"The final prototype iteration is clearly and adequately explained and is constructed with enough detail to assure that objective data on some design requirements could be determined; some attributes (sub-systems) of the unique solution that can be tested or modeled mathematically are addressed and an adequately supported justification is provided for those that cannot be tested or modeled mathematically and thus require expert review."
                ,"The final prototype iteration is explained only somewhat clearly and/or completely and is constructed with enough detail to assure that objective data on at least a few design requirements could be determined; a few attributes (sub- systems) of the unique solution that can be tested or modeled mathematically are addressed but there may be insufficient justification for those that cannot be tested or modeled mathematically and thus require expert review."
                ,"The final prototype iteration is only minimally explained and/or is not constructed with enough detail to assure that objective data on at least one design requirements could be determined; no more than one attribute (sub-system) of the unique solution that can be tested or modeled mathematically is addressed and any attempt at justification for those that cannot be tested or modeled mathematically and thus require expert review is missing."
                ,"Any attempt to explain the final prototype iteration is unclear or is missing altogether; there is no evidence that the prototype would facilitate testing by suitable means for any of the design requirements. Back"]

    ElementH = ["Documentation of plausible prior attempts to solve the problem and/or related problems is drawn from a wide array of clearly identified and consistently credible sources; the analysis of past and current attempts to solve the problem— including both strengths and shortcomings—is consistently clear, detailed, and supported by relevant data. The testing plan addresses all or nearly all of the high priority design requirements by effectively describing the conduct (through physical and/or mathematical modeling) of those tests that are feasible based on the instructional context and providing for others a logical and well-developed explanation confirmed by one or more field experts of how testing would yield objective data regarding the effectiveness of the design."
                ,"The testing plan addresses many of the high priority design requirements by describing in a generally effective way the conduct (through physical and/or mathematical modeling) of those tests that are feasible based on the instructional context and providing for others a logical and generally developed explanation confirmed by one or more field experts of how testing would yield objective data regarding the effectiveness of the design."
                ,"The testing plan addresses some of the high priority design requirements by adequately describing the conduct (through physical and/or mathematical modeling) of those tests that are feasible based on the instructional context and providing for others a generally logical and adequately developed explanation confirmed by one or more field experts of how testing would yield objective data regarding the effectiveness of the design."
                ,"The testing plan addresses a few of the high priority design requirements by at least partially describing the conduct (through physical and/or mathematical modeling) of those tests that are feasible based on the instructional context and providing for others an only somewhat logical and/or partially developed explanation confirmed by one or more field experts of how testing would yield objective data regarding the effectiveness of the design."
                ,"The testing plan addresses one of the high priority design requirements by describing at least minimally the conduct (through physical and/or mathematical modeling) of a test that is feasible based on the instructional context and/or providing for an at least generally logical and/or partially developed explanation of how testing would yield objective data regarding the effectiveness of the design; confirmation of that explanation by even one field expert may be missing."
                ,"Any testing plan included fails to address at least one of the high priority design requirements by describing at least minimally the conduct (through physical and/or mathematical modeling) of a test that is feasible based on the instructional context and/or providing for an at least generally logical and/or partially developed explanation of how testing would yield objective data regarding the effectiveness of the design; OR a testing plan is missing altogether. Back"]

    ElementI = ["Through the conduct of several tests for high priority requirements that are reasonable based on instructional contexts, or through physical or mathematical modeling, the student demonstrates considerable understanding of testing procedure, including the gathering and analysis of resultant data; the analysis of the effectiveness with which the design met stated goals includes a consistently detailed explanation [and summary] of the data from each portion of the testing procedure and from expert reviews, generously supported by pictures, graphs, charts and other visuals; the analysis includes an overall summary of the implications of all data for proceeding with the design and solving the problem."
                ,"Through the conduct of several tests for high priority requirements that are reasonable based on instructional contexts, or through physical or mathematical modeling, the student demonstrates ample understanding of testing procedure, including the gathering and analysis of resultant data; the analysis of the effectiveness with which the design met stated goals includes a generally detailed explanation [and summary] of the data from each portion of the testing procedure and from expert reviews, generally supported by pictures, graphs, charts and other visuals; the analysis includes an overall summary of the implications of most if not all of the data for proceeding with the design and solving the problem."
                ,"Through the conduct of a few tests for high priority requirements that are reasonable based on instructional contexts, or through physical or mathematical modeling, the student demonstrates adequate understanding of testing procedure, including the gathering and analysis of resultant data; the analysis of the effectiveness with which the design met stated goals includes a somewhat detailed explanation [and summary] of the data from each portion of the testing procedure and from expert reviews, at least somewhat supported by pictures, graphs, charts and other visuals; the analysis includes a summary of the implications of at least some of the data for proceeding with the design and solving the problem."
                ,"Through the conduct of one or two tests for high priority requirements that are reasonable based on instructional contexts, or through physical or mathematical modeling, the student demonstrates partial or overly general understanding of testing procedure, including the gathering and analysis of resultant data; the analysis of the effectiveness with which the design met stated goals includes a partial explanation [and summary] of the data (partially complete and/or partially correct), at least minimally supported by pictures, graphs, charts and other visuals; the analysis includes a partial and/or overly-general summary of the implications of at least some of the data for proceeding with the design and solving the problem."
                ,"Through the conduct of one or two tests for requirements (which may or may not be high priority) that are reasonable based on instructional contexts, or through physical or mathematical modeling, the student demonstrates minimal understanding of testing procedure, including the gathering and analysis of resultant data; the analysis of the effectiveness with which the design met stated goals includes an attempted explanation [and summary] of the data but may not be supported by any pictures, graphs, charts or other visuals; the analysis may be missing even a partial and/or overly-general summary of the implications of any of the data for proceeding with the design and solving the problem."
                ,"Any test(s) for requirement(s) or attempts at physical or mathematical modeling fail to demonstrate even minimal understanding of testing procedure, including the gathering and analysis of resultant data; OR there is no evidence of testing or physical or mathematical modeling to address any requirements."]

    ElementJ = ["Documentation of project evaluation by multiple, demonstrably qualified stakeholders and field experts is presented and is synthesized in a consistently specific, detailed, and thorough way; documentation is sufficient in two or more categories to yield meaningful analysis of that evaluation data; the synthesis of evaluations consistently addresses evaluators’ specific questions, concerns, and opinions related to design requirements."
                ,"Documentation of project evaluation by two or more demonstrably qualified stakeholders and field experts is presented and is synthesized in a generally specific, detailed, and thorough way; documentation is sufficient in at least one category to yield a meaningful analysis of that evaluation data; the synthesis of evaluations generally addresses evaluators’ specific questions, concerns, and opinions related to design requirements."
                ,"Documentation of project evaluation by three or four demonstrably qualified stakeholders and/or field experts is presented and is synthesized in a somewhat specific and detailed way, but may not be thorough; documentation may not be sufficient in any category to yield a meaningful analysis of that evaluation data; the synthesis of evaluations addresses at least some of evaluators’ specific questions, concerns, and opinions related to design requirements."
                ,"Documentation of project evaluation by two or three representatives of stakeholders and/or field experts (some of whom may not be demonstrably qualified) is presented and is synthesized in a somewhat specific and/or detailed but incomplete or overly general way; the synthesis of evaluations addresses at least a few of evaluators’ specific questions, concerns, and/or opinions related to design requirements."
                ,"Documentation of project evaluation by one or two representatives of stakeholders and/or field experts is presented but synthesis is sparse, with few specifics/details; the synthesis of evaluations addresses only one or two of an evaluator’s questions, concerns, and/or opinions related to design requirements."
                ,"Documentation of project evaluation by any representative stakeholder or field expert is non-existent OR if included is minimal; synthesis is minimal or missing and if present, does not address any questions, concerns, or opinions of an evaluator related to design requirements."]

    ElementK = ["he project designer provides a consistently clear, insightful, and comprehensive reflection on, and value judgment of, each major step in the project; the reflection includes a substantive summary of lessons learned that would be clearly useful to others attempting the same or similar project."
                ,"The project designer provides a clear, insightful and well-developed reflection on, and value judgment of, each major step in the project; the reflection includes a summary of lessons learned that would be clearly useful to others attempting the same or similar project."
                ,"The project designer provides a generally clear and insightful, adequately- developed reflection on, and value judgment of, major steps in the project, although one or two steps may be addressed in a more cursory manner; the reflection includes a summary of lessons learned, at least most of which would be useful to others attempting the same or similar project."
                ,"The project designer provides a generally clear, at least somewhat insightful, and partially developed reflection on, and value judgment of, most if not all of the major steps in the project; the reflection includes some lessons learned which would be useful to others attempting the same or similar project."
                ,"The project designer provides a reflection on, and value judgment of, at least some of the major steps in the project, although the reflection may be partial, overly-general and/or superficial; the reflection includes a few lessons learned of which at least one would be useful to others attempting the same or similar project."
                ,"The project designer attempts a reflection on, and value judgment of, at least one or two of the major steps in the project, although the reflection may be minimal, unclear, and/or extremely superficial; any lessons learned are unclear and/or of no likely use to others attempting the same or similar project; OR there is no evidence of a reflection and/or lessons learned."]

    ElementL = ["The project designer includes consistently detailed and salient recommendations regarding the conduct of the same or similar project in the future; recommendations include caveats as warranted and specific ways the project could be improved with consistently detailed plans for the implementation of those improvements."
                ,"The project designer includes generally detailed and salient recommendations regarding the conduct of the same or similar project in the future; recommendations include caveats as warranted and specific ways the project could be improved with generally detailed plans for the implementation of those improvements."
                ,"The project designer includes a few detailed and salient recommendations regarding the conduct of the same or similar project in the future; recommendations include some specific ways the project could be improved along with what may be only minimally detailed plans for the implementation of those improvements and may also include one or two caveats for others."
                ,"The project designer includes recommendations regarding the conduct of the same or similar project in the future; recommendations may include some specific ways the project could be improved but plans for the implementation of those improvements may be missing OR the recommendations (with or without plans) may be partial and/or overly general."
                ,"The project designer includes one or two overly general and/or questionably relevant recommendations regarding the conduct of the same or similar project in the future; any plans for implementation included are vague/unclear or minimally related to the recommendations provided."
                ,"The project designer includes one or two recommendations (with or without plans) that bear little/no relation to the conduct of the same or similar project in the future OR fails to offer any recommendations or plans regarding the conduct of the same or similar project in the future."]

                
